"""Tests for security API routes."""

import uuid
from unittest.mock import AsyncMock, MagicMock, patch

import pytest
from httpx import ASGITransport, AsyncClient

# Import the repository model to mock DB calls
from src.db.models.repository import Repository
from src.db.models.security import VulnerabilityScan, Vulnerability


@pytest.fixture
async def client():
    """Create test client."""
    from src.api.main import app

    async with AsyncClient(
        transport=ASGITransport(app=app),
        base_url="http://test"
    ) as client:
        yield client


class TestSecurityEndpoints:
    """Test suite for security API endpoints."""

    @pytest.mark.asyncio
    async def test_trigger_scan_returns_scan_id(self, client: AsyncClient):
        """POST /api/v1/security/{repo_id}/scan should return scan ID."""
        repo_id = str(uuid.uuid4())

        from src.api.main import app
        from src.api.deps import get_db

        mock_db = AsyncMock()
        mock_repo = Repository(id=uuid.UUID(repo_id))
        mock_db.get.return_value = mock_repo

        # When db.add(scan) is called, it sets the ID on the scan object usually if it's not set,
        # but here we manually create it in the route.
        # Wait, the route creates VulnerabilityScan instance.
        # SQLAlchemy models usually have an ID generated by default.
        # In `src/db/base.py`, `id` has `default=uuid.uuid4`.
        # However, `db.add(scan)` is sync in terms of adding to session, but `commit`/`refresh` are async.
        # The ScanResponse schema expects `id` and `started_at`.
        # `started_at` has server_default=func.now().
        # We need to make sure `scan.id` and `scan.started_at` are populated.

        # We can intercept the `db.add` call to verify and maybe set attributes if needed?
        # Or better, just ensure `db.refresh` populates them on the mock object.

        async def mock_refresh(instance):
             if not instance.id:
                 instance.id = uuid.uuid4()
             if not instance.started_at:
                 import datetime
                 instance.started_at = datetime.datetime.now(datetime.timezone.utc)

        mock_db.refresh.side_effect = mock_refresh

        async def override_get_db():
            yield mock_db

        app.dependency_overrides[get_db] = override_get_db

        response = await client.post(
            f"/api/v1/security/{repo_id}/scan",
            json={"full_scan": False},
        )

        app.dependency_overrides = {}

        assert response.status_code == 202
        data = response.json()
        assert "id" in data
        assert data["status"] == "pending"

    @pytest.mark.asyncio
    async def test_list_vulnerabilities(self, client: AsyncClient):
        """GET /api/v1/security/{repo_id}/vulns should return vulnerabilities."""
        repo_id = str(uuid.uuid4())

        from src.api.main import app
        from src.api.deps import get_db

        mock_db = AsyncMock()

        # Mock result for list_vulnerabilities query
        mock_result = MagicMock() # Use MagicMock for the result object
        mock_vuln = Vulnerability(
            id=uuid.uuid4(),
            scan_id=uuid.uuid4(),
            repo_id=uuid.UUID(repo_id),
            cve_id="CVE-2024-1234",
            package_name="lodash",
            severity="high",
            status="open",
            # dates are needed
            first_seen_at="2024-01-01T00:00:00Z",
            created_at="2024-01-01T00:00:00Z",
            updated_at="2024-01-01T00:00:00Z",
        )
        # sqlalchemy execute returns a Result, result.scalars() returns ScalarResult, .all() returns list
        mock_result.scalars.return_value.all.return_value = [mock_vuln]
        mock_db.execute.return_value = mock_result

        async def override_get_db():
            yield mock_db

        app.dependency_overrides[get_db] = override_get_db

        response = await client.get(f"/api/v1/security/{repo_id}/vulns")

        app.dependency_overrides = {}

        assert response.status_code == 200
        data = response.json()
        assert isinstance(data, list)
        assert len(data) == 1
        assert data[0]["cve_id"] == "CVE-2024-1234"

    @pytest.mark.asyncio
    async def test_filter_vulnerabilities_by_severity(self, client: AsyncClient):
        """Should filter vulnerabilities by severity."""
        repo_id = str(uuid.uuid4())

        from src.api.main import app
        from src.api.deps import get_db

        mock_db = AsyncMock()
        mock_result = MagicMock()
        mock_result.scalars.return_value.all.return_value = []
        mock_db.execute.return_value = mock_result

        async def override_get_db():
            yield mock_db

        app.dependency_overrides[get_db] = override_get_db

        response = await client.get(
            f"/api/v1/security/{repo_id}/vulns",
            params={"severity": "critical"},
        )

        app.dependency_overrides = {}

        assert response.status_code == 200

        mock_db.execute.assert_called_once()
