"""GitHub PR commenting functionality."""
from __future__ import annotations

from typing import Any, List, Dict
try:
    from github import Github, GithubException
except ImportError:
    # Mock for environment without PyGitHub installed or for tests
    Github = Any
    GithubException = Exception


class GitHubCommenter:
    """Posts comments to GitHub PRs."""

    def __init__(self, app_client: Github):
        self.github = app_client

    async def post_review_comment(
        self,
        repo_full_name: str,
        pr_number: int,
        review_summary: dict,
    ) -> str:
        """Post review summary as PR comment."""
        repo = self.github.get_repo(repo_full_name)
        pr = repo.get_pull(pr_number)

        body = self._format_review_comment(review_summary)

        comment = pr.create_issue_comment(body)
        return comment.html_url

    async def post_inline_comments(
        self,
        repo_full_name: str,
        pr_number: int,
        comments: List[dict],
        commit_sha: str,
    ) -> int:
        """Post inline review comments."""
        repo = self.github.get_repo(repo_full_name)
        pr = repo.get_pull(pr_number)
        commit = repo.get_commit(commit_sha)

        posted_count = 0
        for comment in comments:
            try:
                pr.create_review_comment(
                    body=self._format_inline_comment(comment),
                    commit=commit,
                    path=comment["file_path"],
                    line=comment["line_number"],
                )
                posted_count += 1
            except GithubException:
                # Log error but continue
                pass
            except Exception:
                 # Fallback for other errors
                 pass

        return posted_count

    async def create_check_run(
        self,
        repo_full_name: str,
        head_sha: str,
        name: str,
        conclusion: str,
        summary: str,
    ) -> str:
        """Create a GitHub Check Run."""
        repo = self.github.get_repo(repo_full_name)

        check_run = repo.create_check_run(
            name=name,
            head_sha=head_sha,
            status="completed",
            conclusion=conclusion,
            output={
                "title": name,
                "summary": summary,
            },
        )

        return check_run.html_url

    def _format_review_comment(self, review: dict) -> str:
        """Format review as markdown comment."""
        blockers = review.get("blocker_count", 0)
        warnings = review.get("warning_count", 0)
        suggestions = review.get("suggestion_count", 0)

        verdict = "✅ Approved" if blockers == 0 else "❌ Changes Requested"

        return f"""## 🤖 DevMind Code Review

{verdict}

### Summary
| Category | Count |
|----------|-------|
| 🔴 Blocker | {blockers} |
| 🟠 Warning | {warnings} |
| 🟡 Suggestion | {suggestions} |

{review.get('summary', '')}

---
*Generated by [DevMind AI](https://devmind.ai)*
"""

    def _format_inline_comment(self, comment: dict) -> str:
        """Format inline comment."""
        severity_icons = {
            "blocker": "🔴",
            "warning": "🟠",
            "suggestion": "🟡",
            "nit": "💡",
        }

        icon = severity_icons.get(comment.get("severity", ""), "")
        title = comment.get("title", "Issue")
        message = comment.get("message", "")
        suggestion = comment.get("suggestion", "")

        body = f"{icon} **{title}**\n\n{message}"

        if suggestion:
            body += f"\n\n💡 **Suggestion:**\n```suggestion\n{suggestion}\n```"

        return body
